version: '3.7'

services:
  node:
    build: ./docker/node
    volumes:
      - './app:/app'
      - './logs/npm:/root/.npm/_logs/'
    ports:
      - '8085:8080'
    env_file:
      - .env
    stdin_open: true
    tty: true
