version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - cd ./app && sh ./AWS-ssm.sh
      - echo Install dependencies
      - npm install
  build:
    commands:
      - npm run webpack:build
artifacts:
  files:
    - "app/dist/*"
    - "app/dist/**/*"