version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - sh AWS-ssm.sh
      - echo Install dependencies
      - npm install
  build:
    commands:
      - npm run webpack:build
    on-failure: ABORT
  post_build:
    commands:
      - aws s3 cp --recursive --acl public-read ./dist s3://myq-front-prod/
      - aws s3 cp --acl public-read --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./dist/index.html s3://myq-front-prod/
      - echo Build completed on `date`
artifacts:
  files:
    - "dist/*"
    - "dist/**/*"