version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - cd ./app && sh ./AWS-ssm.sh
      - echo Install dependencies
      - npm install
  build:
    commands:
      - npm run webpack:build
    on-failure: ABORT
  post_build:
    commands:
      - aws s3 sync ./dist $S3_BUCKET
      - echo Build completed on `date`
artifacts:
  files:
    - "app/dist/*"
    - "app/dist/**/*"